plotter/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path('directories/', views.directory_list, name='directory_list'),
    path('folders/<int:directory_id>/', views.folder_list, name='folder_list'),
    path('generate_picture/<int:folder_id>/', views.generate_picture_view, name='generate_picture'),
]

plotview/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("polls/", include("polls.urls")),
    path("plotter/", include("plotter.urls")),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

app_name = "polls"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

plotter/models.py
from django.db import models

# Create your models here.

class Directory(models.Model):
    path = models.CharField(max_length=255)

class Folder(models.Model):
    directory = models.ForeignKey(Directory, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    picture = models.ImageField(upload_to='pictures/', blank=True, null=True)

polls/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.contrib import admin

# Create your models here.



class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")
    
    def __str__(self):
        return self.question_text
    
    @admin.display(
        boolean=True,
        ordering="pub_date",
        description="Published recently?",
    )
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    
    def __str__(self):
        return self.choice_text
    
    

plotter/forms.py
from django import forms
from .models import Directory

class DirectoryForm(forms.ModelForm):
    class Meta:
        model = Directory
        fields = ['path']

plotter/views.py
from django.shortcuts import render

from django.shortcuts import render, get_object_or_404, redirect
from .models import Directory, Folder
from .utils import plot_data
from django.views import generic
import os


def directory_list(request):
    directories = Directory.objects.all()
    return render(request, 'plotter/directory_list.html', {'directories': directories})

def folder_list(request, directory_id):
    directory = get_object_or_404(Directory, pk=directory_id)
    
    # Get a list of all folders in the directory on the filesystem
    directory_path = directory.path
    directory_folders = os.listdir(directory_path)
    
    # Get a list of all folders stored in the database for this directory
    db_folders = Folder.objects.filter(directory=directory)
    
    # Create a set of folder names for quick comparison
    directory_folder_names = set(directory_folders)
    db_folder_names = set(folder.name for folder in db_folders)
    
    # Find new folders in the directory and add them to the database
    new_folders = directory_folder_names - db_folder_names
    for folder_name in new_folders:
        Folder.objects.create(directory=directory, name=folder_name)
    
    # Find folders in the database that no longer exist in the directory and delete them
    deleted_folders = db_folder_names - directory_folder_names
    Folder.objects.filter(directory=directory, name__in=deleted_folders).delete()
    
    # Get the updated list of folders for this directory
    folders = Folder.objects.filter(directory=directory).order_by('-name')
    
    return render(request, 'plotter/folder_list.html', {'directory': directory, 'folders': folders})


def generate_picture_view(request, folder_id):
    folder = get_object_or_404(Folder, pk=folder_id)
    plot_data(folder)
    return redirect('folder_list', directory_id=folder.directory.pk)


class IndexView(generic.ListView):
    template_name = "plotter/index.html"
    context_object_name = "directories"
    
    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Directory.objects.order_by("-path")

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from .models import Question, Choice
from django.http import Http404
from django.urls import reverse
from django.views import generic
from django.utils import timezone

def index(request):
    latest_question_list = Question.objects.order_by("-pub_date")[:5]
    template = loader.get_template("polls/index.html")
    context = {
        "latest_question_list": latest_question_list,
    }
    return HttpResponse(template.render(context, request))

#def index(request):
#    return HttpResponse("Hello, world. You're at the polls index.")

def detail(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    return render(request, "polls/detail.html", {"question": question})


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "polls/results.html", {"question": question})



def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request,
            "polls/detail.html",
            {
                "question": question,
                "error_message": "You didn't select a choice.",
            },
        )
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))


class IndexView(generic.ListView):
    template_name = "polls/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by("-pub_date")[
            :5
        ]



class DetailView(generic.DetailView):
    model = Question
    template_name = "polls/detail.html"


class ResultsView(generic.DetailView):
    model = Question
    template_name = "polls/results.html"


# Create your views here.

plotter/templates/plotter/directory_list.html
{% load static %}
<link rel="stylesheet" href="{% static 'plotter/style.css' %}">

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Directory List</title>
</head>
<body>
    <h1>Directory List</h1>
    <ul>
        {% for directory in directories %}
            <li>
                <a href="{% url 'folder_list' directory.id %}">{{ directory.path }}</a>
            </li>
        {% endfor %}
    </ul>
</body>
</html>

plotter/templates/plotter/folder_list.html
{% load static %}
<link rel="stylesheet" href="{% static 'plotter/style.css' %}">

{% for folder in folders %}
<div>
    <h2>{{ folder.name }}</h2>
    <button onclick="location.href='{% url 'generate_picture' folder.id %}'">Plot</button>
    {% if folder.picture %}
    <details>
        <summary>
            <span class="icon">\/</span>
        </summary>
        <img src="{% static folder.picture ".png" %}" alt="{{ folder.name }} Picture">
    </details>
    {% endif %}
</div>
{% endfor %}

plotter/templates/plotter/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Directory List</title>
</head>
<body>
    <h1>Directory List</h1>
    <ul>
        {% for directory in directories %}
            <li>
                <a href="{% url 'folder_list' directory.id %}">{{ directory.path }}</a>
            </li>
        {% endfor %}
    </ul>
</body>
</html>

polls/templates/polls/detail.html
<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
</form>
<a href="{% url 'polls:index' %}">back to all questions</a>

polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" href="{% static 'polls/style.css' %}">


{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?<br></a>
<a href="{% url 'polls:index' %}">back to all questions</a>